### ISSUE TITLE
why not client return?

### ISSUE THREAD

**Issue by tangjielong** [jb55/node-bitcoin#15]
var shdh = client.getInfo(function (err, info) {
    console.log(info);
    return info;
});
console.log(shdh);

console say shdh=underfine?

**Comment by jb55** [comment]
this is an abandoned branch of node-bitcoin, did you mean to submit this to https://github.com/freewil/node-bitcoin ?

**Comment by tangjielong** [comment]
yeah，i think mean to submit this is well.
